# Generated by Django 4.2.2 on 2023-07-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(default='', max_length=10)),
                ('Password', models.CharField(default='', max_length=20)),
                ('Email', models.CharField(default='', max_length=20)),
                ('Image', models.ImageField(default='Notes/Notes/static/Notepad/default_user_img.png', upload_to='')),
            ],
        ),
    ]
