# Generated by Django 4.2.2 on 2023-07-01 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notepad', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_profile',
        ),
    ]
