# Generated by Django 4.2.2 on 2023-07-01 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Notepad', '0002_rename_user_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='Username',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
