# Generated by Django 4.2.2 on 2023-07-04 15:52

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Notepad', '0005_alter_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(default='Note', max_length=30)),
                ('Last_edited', models.DateTimeField(auto_now=True)),
                ('Image', models.ImageField(default='Notepad/default_notes-img.jpg', upload_to='Notes/Notes/media/Notepad')),
                ('Text', ckeditor.fields.RichTextField()),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
