# Generated by Django 4.2.2 on 2023-07-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notepad', '0008_alter_note_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='Title',
            field=models.CharField(default='Note', max_length=130),
        ),
    ]
